# Generated by Django 2.0.2 on 2018-04-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
